---
- name: Delete a user's public key
  hosts: all
  become: true

  vars:
    root_username: "root"

  vars_prompt:
    - name: username
      prompt: "username"
      private: false

    - name: key
      prompt: "public key"
      private: false

  pre_tasks:
    - name: Don't allow modifying current user's keys
      ansible.builtin.fail:
        msg: >-
          To avoid the risk of bricking a server, you can't use this Playbook to modify keys for the user Ansible logs in as.
          If you really need to do this, please do it manually or use user/add_key.yaml instead.
      when: username | lower == ansible_user

    - name: Refuse to modify root keys
      ansible.builtin.fail:
        msg: >-
          You can't modify the root account's authorised keys.
      when: username | lower == root_username

  tasks:
    - name: Delete the key from authorized_keys
      ansible.posix.authorized_key:
        key: "{{ key }}"
        user: "{{ username }}"
        manage_dir: true # Ansible will sort out permissions and create directories if needed
        state: absent